/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 用户登录 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            username?: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description 登录成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiOk'];
          };
        };
        /** @description 参数验证失败 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description 认证失败 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 修改当前用户密码 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            newPassword: string;
          };
        };
      };
      responses: {
        /** @description 修改成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiOk'];
          };
        };
        /** @description 参数验证失败 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description 未授权 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/favorites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取全部收藏 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 返回收藏映射 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FavoriteMap'] & {
              [key: string]: components['schemas']['FavoriteItem'] & {
                title?: string;
                source_name?: string;
                /** @default  */
                year: string;
                /** @default  */
                cover: string;
                /** @default 0 */
                total_episodes: number;
                /** @default 1771118842904 */
                save_time: number;
                search_title?: string;
                /** @enum {string} */
                origin?: 'vod' | 'live';
              };
            };
          };
        };
        /** @description 未授权 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** 保存收藏 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            key: string;
            favorite: {
              title: string;
              source_name: string;
              /** @default  */
              year?: string;
              /** @default  */
              cover?: string;
              /** @default 0 */
              total_episodes?: number;
              /** @default 1771118842904 */
              save_time?: number;
              search_title?: string;
              /** @enum {string} */
              origin?: 'vod' | 'live';
            };
          };
        };
      };
      responses: {
        /** @description 保存成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiSuccess'];
          };
        };
        /** @description 参数验证失败 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    /** 删除收藏（单条或全部） */
    delete: {
      parameters: {
        query?: {
          key?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 删除成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiSuccess'];
          };
        };
        /** @description 参数错误 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description 未授权 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/playrecords': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取播放记录 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 返回播放记录映射 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PlayRecordMap'] & {
              [key: string]: components['schemas']['PlayRecordItem'] & {
                title?: string;
                source_name?: string;
                /** @default  */
                year: string;
                /** @default  */
                cover: string;
                /** @default 0 */
                index: number;
                /** @default 0 */
                total_episodes: number;
                /** @default 0 */
                play_time: number;
                /** @default 0 */
                total_time: number;
                /** @default 1771118842905 */
                save_time: number;
                search_title?: string;
              };
            };
          };
        };
        /** @description 未授权 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** 保存播放记录 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            key: string;
            record: {
              title: string;
              source_name: string;
              /** @default  */
              year?: string;
              /** @default  */
              cover?: string;
              /** @default 0 */
              index?: number;
              /** @default 0 */
              total_episodes?: number;
              /** @default 0 */
              play_time?: number;
              /** @default 0 */
              total_time?: number;
              /** @default 1771118842905 */
              save_time?: number;
              search_title?: string;
            };
          };
        };
      };
      responses: {
        /** @description 保存成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiSuccess'];
          };
        };
        /** @description 参数验证失败 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    /** 删除播放记录（单条或全部） */
    delete: {
      parameters: {
        query?: {
          key?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 删除成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiSuccess'];
          };
        };
        /** @description 参数错误 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description 未授权 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/searchhistory': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取搜索历史 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 返回搜索历史列表 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string[];
          };
        };
        /** @description 未授权 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** 新增搜索历史 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            keyword: string;
          };
        };
      };
      responses: {
        /** @description 返回更新后的历史列表 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string[];
          };
        };
        /** @description 参数验证失败 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    /** 删除搜索历史（单条或全部） */
    delete: {
      parameters: {
        query?: {
          keyword?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 删除成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiSuccess'];
          };
        };
        /** @description 未授权 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/skipconfigs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取全部跳过片头片尾配置 */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 返回配置映射 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SkipConfigMap'];
          };
        };
        /** @description 未授权 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    put?: never;
    /** 保存跳过片头片尾配置 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            key: string;
            config: {
              /** @default true */
              enable?: boolean;
              /** @default 0 */
              intro_time?: number;
              /** @default 0 */
              outro_time?: number;
            };
          };
        };
      };
      responses: {
        /** @description 保存成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiSuccess'];
          };
        };
        /** @description 参数验证失败 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    /** 删除单条跳过片头片尾配置 */
    delete: {
      parameters: {
        query: {
          key: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 删除成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiSuccess'];
          };
        };
        /** @description 参数错误 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
        /** @description 未授权 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiError'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiError: {
      error: string;
    };
    ApiOk: {
      ok: boolean;
    };
    ApiSuccess: {
      success: boolean;
    };
    FavoriteItem: {
      title: string;
      source_name: string;
      /** @default  */
      year: string;
      /** @default  */
      cover: string;
      /** @default 0 */
      total_episodes: number;
      /** @default 1771118842901 */
      save_time: number;
      search_title?: string;
      /** @enum {string} */
      origin?: 'vod' | 'live';
    };
    PlayRecordItem: {
      title: string;
      source_name: string;
      /** @default  */
      year: string;
      /** @default  */
      cover: string;
      /** @default 0 */
      index: number;
      /** @default 0 */
      total_episodes: number;
      /** @default 0 */
      play_time: number;
      /** @default 0 */
      total_time: number;
      /** @default 1771118842902 */
      save_time: number;
      search_title?: string;
    };
    SkipConfigItem: {
      /** @default true */
      enable: boolean;
      /** @default 0 */
      intro_time: number;
      /** @default 0 */
      outro_time: number;
    };
    FavoriteMap: {
      [key: string]: components['schemas']['FavoriteItem'] & {
        title?: string;
        source_name?: string;
        /** @default  */
        year: string;
        /** @default  */
        cover: string;
        /** @default 0 */
        total_episodes: number;
        /** @default 1771118842902 */
        save_time: number;
        search_title?: string;
        /** @enum {string} */
        origin?: 'vod' | 'live';
      };
    };
    PlayRecordMap: {
      [key: string]: components['schemas']['PlayRecordItem'] & {
        title?: string;
        source_name?: string;
        /** @default  */
        year: string;
        /** @default  */
        cover: string;
        /** @default 0 */
        index: number;
        /** @default 0 */
        total_episodes: number;
        /** @default 0 */
        play_time: number;
        /** @default 0 */
        total_time: number;
        /** @default 1771118842903 */
        save_time: number;
        search_title?: string;
      };
    };
    SkipConfigMap: {
      [key: string]: components['schemas']['SkipConfigItem'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
